* About
This plugin allows mpv to stream magnet links (and any other torrent identifier [[https://github.com/webtorrent/webtorrent-cli][webtorrent-cli]] handles) directly. It will automatically remove videos after they are finished playing (by default) and will set the title to be the name of the video.

This script will detect =magnet:= links and torrent files/urls ending in =torrent= passed to mpv by default. For any other torrent identifier supported by webtorrent, prefix the identifier with =webtorrent://=.

One reason you might want to use this script over calling ~webtorrent --mpv~ is that you can start mpv with a playlist of multiple magnet links or add magnet links to the playlist of an already open mpv window (e.g. using one of the scripts that allow appending a link from the clipboard to the playlist).

By using this script, you can also see mpv output (which is hidden when calling ~webtorrent~ directly). On the other hand, you won't be able to see both the normal ~webtorrent~ output and mpv's output at the same time. By default, this script will print the download speed while waiting for the video to load (see the information on the =webtorrent_verbosity= setting below for more options).

* Requirements
- [[https://github.com/webtorrent/webtorrent-cli][webtorrent-cli]]
- on linux (or maybe similar)
- basic shell utilities (awk and tail)

* Advantages Over Peerflix
Peerflix is unmaintained, and webtorrent is supposedly significantly faster.

Peerflix's output is not parseable, so the peerflix version of this script had to do a bunch of extra work with ~lsof~ to figure out the location of video files, the title of video files, and the process id of peerflix (in order to kill it). This script is a lot cleaner by comparison (though it could be better if webtorrent had a way to give [[https://github.com/webtorrent/webtorrent-cli/issues/132][more script-friendly output]]).

* Disadvantages and Limitations
Webtorrent has parseable output but is still not very script friendly. [[https://github.com/noctuid/mpv-btfs-stream][mpv-btfs-stream]] is cleaner and simpler by comparison and does not rely on parsing output. The advantage of webtorrent over btfs is that webtorrent is much faster. See [[https://github.com/noctuid/mpv-btfs-hook#comparison-with-mpv-webtorrent-hook][here]] for a full comparison.

Currently torrents that have multiple media files will not work correctly. Changes to webtorrent-cli are necessary to make this easily possible. If you need this functionality, you can use [[https://github.com/noctuid/mpv-btfs-stream][mpv-btfs-stream]] just for torrents that contain multiple videos or images.

* Comparison with webtorrent-mpv-hook
There is a similarly named plugin [[https://github.com/mrxdst/webtorrent-mpv-hook][webtorrent-mpv-hook]] which directly uses the webtorrent library instead of webtorrent-cli. It supports torrent containing multiple video files and has a much nicer progress display. This is much preferable, and I am hoping to deprecate this plugin in the future and recommend webtorrent-mpv-hook instead.

Here are the features it is currently missing that this plugin or btfs-stream have:
- [ ] no option to delete files after exiting mpv
- [ ] does not work correctly with scripts that allow pasting a path/url into the playlist
- [ ] does not support =~/= and other mpv path abbreviations in the path setting for where to download to
- [ ] does not support displaying torrents of images (maybe just torrents with a zip of images)

* Configuration
In =~/.config/mpv/script-opts/webtorrent-hook.conf=, you can change the following settings:
- =close_webtorrent= - whether to close webtorrent after unloading the video; if =no=, keep seeding (default: =yes=)
- =remove_files= - whether to remove the video file from disk after unloading; =yes= only has an effect if =close_webtorrent= is also =yes= (default: =yes=)
- =download_directory= - directory to download videos to; the script will run mpv's =expand-path= command on the string first so that mpv path abreviations such as =~/= and =~~/= can be used (default: =/tmp/webtorrent=)
- =webtorrent_flags= - string of extra flags to pass to webtorrent (default: ""; flags always used: =webtorrent --out <download_directory> --keep-streaming=; keep-streaming is always passed, and =close_webtorrent= determines whether or not to stop webtorrent)
- =webtorrent_verbosity= - verbosity level of webtorrent output; output is stopped once the video is loaded to prevent clobbering mpv's output; output webtorrent's download speed line if =speed=; output nothing if =quiet= (default: =speed=)
